name: Build Kernel

on:
  push:
    branches: [ action_test ]
  pull_request:
    branches: [ action_test ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Install dependencies
        run: git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7

      - name: Build Kernel
        run: |
          echo "Using ${JOBS} threads"
          make -j${JOBS} ${DEFCONFIG} > /dev/null && make -j${JOBS} > /dev/null
        env:
          ARCH: arm
          CROSS_COMPILE: ${GITHUB_WORKSPACE}/arm-eabi-4.7/bin/arm-eabi-
          DEFCONFIG: cyanogenmod_manta_defconfig
          JOBS: $(nproc)
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: zImage
          path: arch/arm/boot/zImage
