name: Build cm-13.0 Kernel

on:
  workflow_dispatch: null
  push:
    branches:
      - 'stable/cm-13.0-ZNH5Y-dt2w'
  pull_request:
    branches:
      - 'stable/cm-13.0-ZNH5Y-dt2w'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Install toolchain
        run: git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7

      - name: Build Kernel
        run: |
          echo "Using $(nproc) threads"
          make -j$(nproc) ${DEFCONFIG} > /dev/null && make -j$(nproc) > /dev/null
        env:
          ARCH: arm
          CROSS_COMPILE: ${{ github.workspace }}/arm-eabi-4.7/bin/arm-eabi-
          DEFCONFIG: cyanogenmod_manta_defconfig
          JOBS: $(nproc)
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: zImage
          path: arch/arm/boot/zImage
